### PR TITLE
Added button styling to game window and fixed cascading bug

### LINKED ISSUE #6: Automatically reveal empty regions
When clicking on a cell that has no neighboring bombs, expand all neighboring cells. Repeat this recursively for all cells with no neighboring bombs

### LINKED ISSUE #16: Custom button style to avoid unwanted style
Currently when the window size reaches a certain aspect ratio that is too 'weird' for the grid size, swing tries to fix that by setting the button style to a more rounded style with a large gap between buttons (at least on MacOS). This is sort of a bug but we can fix it by creating our own style for buttons that is the same cross-platform, and also allows us to extend the program further by having a neater UI.

### PR DESCRIPTION
**Pull request by Azgorn**
The pull request implements a recursive method fix that closes issue #21 and implements styling for the buttons during gameplay and closes #22

### CODE REVIEW

File: Minesweeper.java [hunk 1]
```diff
@@ -32,12 +32,21 @@ public void actionPerformed(ActionEvent e) {
         }
 
         void setNeighboringBombs(int neighboringBombs) {
+            
             this.neighboringBombs = neighboringBombs;
             setText(String.valueOf(this.neighboringBombs));
         }
+        
+        int getNeighboringBombs(Cell cell){
```
Comment (pbogre) [inline Minesweeper.java]: we should get rid of this function and just call `computeNeighboringBombs` from within `Game` rather than just having a function in `Cell` that links back to `Game`.

File: Minesweeper.java [hunk 2]
```diff
@@ -81,24 +105,57 @@ private void run() {
...
+
+
         private void populateBombs() {
             Random random = new Random();
             int remainingBombs = this.bombAmount;
 
             while (remainingBombs > 0) {
-                int randomColumn = random.nextInt(this.gridSize);
-                int randomRow = random.nextInt(this.gridSize);
+                int randomColumn = random.nextInt(Game.gridSize);
```
Comment (pbogre) [inline Minesweeper.java]: why did we switch to using referencing `Game` instead of `this`? Was it to be able to make the `getNeighboringBombs` method in the `Cell` class?
```suggestion
                int randomColumn = random.nextInt(this.gridSize);
```

File: Minesweeper.java [hunk 3]
```diff
@@ -62,13 +71,28 @@ public boolean equals(Object obj) {
...
+            else {
+                setBackground(Color.LIGHT_GRAY);
+                setBorder(BorderFactory.createRaisedBevelBorder());
+            }
+        }
     }
   
     private class Game extends JFrame{
-        private int gridSize;
+        private static int gridSize;
```
Comment (pbogre) [inline Minesweeper.java]: this change isn't needed if we use `this` instead of `Game`, which we can if we get rid of the `getNeighboringBombs` method from `Cell`.
```suggestion
        private int gridSize;
```

File: Minesweeper.java [hunk 4]
```diff
@@ -62,13 +71,28 @@ public boolean equals(Object obj) {
...
         private int cellSize;
         private int bombAmount;
-        private Cell[][] cells;
+        private static Cell[][] cells;
```
Comment (pbogre) [inline Minesweeper.java]: this change isn't needed if we use `this` instead of `Game`, which we can if we get rid of the `getNeighboringBombs` method from `Cell`.
```suggestion
        private Cell[][] cells;
```

File: Minesweeper.java [hunk 5]
```diff
@@ -81,24 +105,57 @@ private void run() {
...
                 }
 
-                this.cells[randomRow][randomColumn].makeBomb();
+                Game.cells[randomRow][randomColumn].makeBomb();
                 remainingBombs--;
             }
         }
 
-        private void computeNeighboringBombs(Cell cell) {
+        private static int computeNeighboringBombs(Cell cell) {
```
Comment (pbogre) [inline Minesweeper.java]: this change isn't needed if we use `this` instead of `Game`, which we can if we get rid of the `getNeighboringBombs` method from `Cell`.
```suggestion
        private int computeNeighboringBombs(Cell cell) {
```

File: Minesweeper.java [hunk 6]
```diff
@@ -81,24 +105,57 @@ private void run() {
...
+
         private void populateBombs() {
             Random random = new Random();
             int remainingBombs = this.bombAmount;
 
             while (remainingBombs > 0) {
-                int randomColumn = random.nextInt(this.gridSize);
-                int randomRow = random.nextInt(this.gridSize);
+                int randomColumn = random.nextInt(Game.gridSize);
+                int randomRow = random.nextInt(Game.gridSize);
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
                int randomRow = random.nextInt(this.gridSize);
```

File: Minesweeper.java [hunk 7]
```diff
@@ -81,24 +105,57 @@ private void run() {
...
                 
-                if (this.cells[randomRow][randomColumn].isBomb) {
+                if (Game.cells[randomRow][randomColumn].isBomb) {
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
                if (this.cells[randomRow][randomColumn].isBomb) {
```

File: Minesweeper.java [hunk 8]
```diff
@@ -81,24 +105,57 @@ private void run() {
...
                     continue;
                 }
 
-                this.cells[randomRow][randomColumn].makeBomb();
+                Game.cells[randomRow][randomColumn].makeBomb();
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
                this.cells[randomRow][randomColumn].makeBomb();
```

File: Minesweeper.java [hunk 9]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
                         continue;
                     }
                     // skip out of bounds cases
-                    if(y < 0 || x < 0 || y >= this.gridSize || x >= this.gridSize) {
+                    if(y < 0 || x < 0 || y >= Game.gridSize || x >= Game.gridSize) {
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
                    if(y < 0 || x < 0 || y >= this.gridSize || x >= this.gridSize) {
```

File: Minesweeper.java [hunk 10]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
...
                         continue;
                     }
 
-                    if (this.cells[y][x].isBomb) {
+                    if (Game.cells[y][x].isBomb) {
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
                    if (this.cells[y][x].isBomb) {
```

File: Minesweeper.java [hunk 11]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
...
             }
-
             cell.setNeighboringBombs(neighboringBombs);
+            return neighboringBombs;
         }
 
         public Game(int gridSize, int bombAmount){
             this.cellSize = 35;
-            this.gridSize = gridSize;
+            Game.gridSize = gridSize;
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
            this.gridSize = gridSize;
```

File: Minesweeper.java [hunk 12]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
...
             this.bombAmount = bombAmount;
-            this.cells = new Cell[this.gridSize][this.gridSize];
+            Game.cells = new Cell[Game.gridSize][Game.gridSize];
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
            this.cells = new Cell[this.gridSize][this.gridSize];
```

File: Minesweeper.java [hunk 13]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
...
 
-            setSize(this.gridSize * this.cellSize, this.gridSize * this.cellSize);
-            setLayout(new GridLayout(this.gridSize, this.gridSize));
+            setSize(Game.gridSize * this.cellSize, Game.gridSize * this.cellSize);
```
Comment (pbogre) [inline Minesweeper.java]: why are we using a mix of `this` and `Game` here?
```suggestion
            setSize(this.gridSize * this.cellSize, this.gridSize * this.cellSize);
```

File: Minesweeper.java [hunk 14]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
...
+            setLayout(new GridLayout(Game.gridSize, Game.gridSize));
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
            setLayout(new GridLayout(this.gridSize, this.gridSize));
```

File: Minesweeper.java [hunk 15]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
...
 
-            for (int y = 0; y < this.gridSize; y++) {
-                for (int x = 0; x < this.gridSize; x++) {
+            for (int y = 0; y < Game.gridSize; y++) {
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
            for (int y = 0; y < this.gridSize; y++) {
```

File: Minesweeper.java [hunk 16]
```diff
@@ -109,31 +166,32 @@ private void computeNeighboringBombs(Cell cell) {
...
+                for (int x = 0; x < Game.gridSize; x++) {
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
                for (int x = 0; x < this.gridSize; x++) {
```

File: Minesweeper.java [hunk 17]
```diff
@@ -142,23 +200,23 @@ public Game(int gridSize, int bombAmount){
 
             // must be done after bomb population 
             // as bombs have a separate action listener
-            for (int y = 0; y < this.gridSize; y++) {
-                for (int x = 0; x < this.gridSize; x++) {
+            for (int y = 0; y < Game.gridSize; y++) {
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
            for (int y = 0; y < this.gridSize; y++) {
```

File: Minesweeper.java [hunk 18]
```diff
@@ -142,23 +200,23 @@ public Game(int gridSize, int bombAmount){
...
+                for (int x = 0; x < Game.gridSize; x++) {
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
                for (int x = 0; x < this.gridSize; x++) {
```

File: Minesweeper.java [hunk 19]
```diff
@@ -142,23 +200,23 @@ public Game(int gridSize, int bombAmount){
...
 
                     if (!cell.isBomb) {
+                        final int x2 = x;
+                        final int y2 = y;
                         cell.addActionListener(new ActionListener() {
                             @Override
                             public void actionPerformed(ActionEvent e) {
-                                self.computeNeighboringBombs(cell);
-                                cell.reveal();
+                                Game.computeNeighboringBombs(cell);
```
Comment (pbogre) [inline Minesweeper.java]: note that this also means bringing back the `final Game self = this;` line
```suggestion
                                self.computeNeighboringBombs(cell);
```

File: Minesweeper.java [hunk 20]
```diff
@@ -81,24 +105,57 @@ private void run() {
...
+            if (cell.isRevealed || cell.isBomb) {
+                return;
+            }
+            
+            // Reveal the cell
+            Game.cells[row][col].reveal();
+            
+
+            // If this cell has no adjacent mines, recursively reveal its neighbors
+            if (cell.getNeighboringBombs(Game.cells[row][col]) == 0) {
```
Comment (pbogre) [inline Minesweeper.java]: just use the `Game` method for this
```suggestion
            if (computeNeighboringBombs(this.cells[row][col]) == 0) {
```

File: Minesweeper.java [hunk 21]
```diff
@@ -81,24 +105,57 @@ private void run() {
...
+                // Define relative positions of neighboring cells
+                int[] dr = {-1, -1, -1, 0, 1, 1, 1, 0};
```
Comment (pbogre) [inline Minesweeper.java]: how is this method better than an iteration across the x and y neighbors of the cell, which is more readable?

File: Minesweeper.java [hunk 22]
```diff
@@ -142,23 +200,23 @@ public Game(int gridSize, int bombAmount){
...
             // as bombs have a separate action listener
-            for (int y = 0; y < this.gridSize; y++) {
-                for (int x = 0; x < this.gridSize; x++) {
+            for (int y = 0; y < Game.gridSize; y++) {
+                for (int x = 0; x < Game.gridSize; x++) {
                     final Cell cell = cells[y][x];
-                    final Game self = this;
 
                     if (!cell.isBomb) {
+                        final int x2 = x;
```
Comment (pbogre) [inline Minesweeper.java]: there has to be a better way of doing this right? this is not only counterintuitive but also hard to read: "why is a variable named `x2` equal to `x`?".

**Review by pbogre — CHANGES_REQUESTED** [review]

File: Minesweeper.java (hunk 1 above)
Comment (Azgorn) [reply Minesweeper.java]: i agree

File: Minesweeper.java (hunk 2 above)
Comment (Azgorn) [reply Minesweeper.java]: yeah it needed to be static, it can be reverted to this

File: Minesweeper.java (hunk 22 above)
Comment (Azgorn) [reply Minesweeper.java]: since the actionlistener is an inner "class" when variables outside it, i.e the counters from the loops y and x are given to it as parameters in the method, it wants them to be final or effectively final, thats why those two new variables are created, i agree that we can/should rename them

Comment (pbogre) [reply Minesweeper.java]: is it possible to do `final int x = x`?

File: Minesweeper.java (hunk 21 above)
Comment (Azgorn) [reply Minesweeper.java]: that's just the absolute values for the 9x9 grid encapsulating the cell, for me it makes more sense since we just a single for loop to check things

File: Minesweeper.java (hunk 22 above)
Comment (Azgorn) [reply Minesweeper.java]: im not really sure, i dont know if java would like the same variable name and if it will distinguish between the two. we could just call them xFinal/yFinal

Comment (pbogre) [reply Minesweeper.java]: addressed in latest commit

File: Minesweeper.java (hunk 21 above)
Comment (pbogre) [reply Minesweeper.java]: you are using a single loop but that doesn't make it any faster because the logic is the same. the double for loop for neighboring cells will always only go through 8 (technically 9 but one is always skipped) cells so it is not quadratic

File: Minesweeper.java [hunk 23]
```diff
@@ -32,12 +32,16 @@ public void actionPerformed(ActionEvent e) {
         }
 
         void setNeighboringBombs(int neighboringBombs) {
+            
             this.neighboringBombs = neighboringBombs;
             setText(String.valueOf(this.neighboringBombs));
         }
-
+
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion

```

File: Minesweeper.java [hunk 24]
```diff
@@ -32,12 +32,16 @@ public void actionPerformed(ActionEvent e) {
         }
 
         void setNeighboringBombs(int neighboringBombs) {
+
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
```

File: Minesweeper.java [hunk 25]
```diff
@@ -81,6 +100,39 @@ private void run() {
...
+            Cell cell = this.cells[row][col];
+            
+            // Check if the cell is already revealed or contains a mine
+            if (cell.isRevealed || cell.isBomb) {
+                return;
+            }
+            
+            // Reveal the cell
+            this.cells[row][col].reveal();
+
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
```

File: Minesweeper.java [hunk 26]
```diff
@@ -81,6 +100,39 @@ private void run() {
...
+                
+                for (int i = 0; i < 8; i++) {
+                    int newRow = row + dr[i];
+                    int newCol = col + dc[i];
+                    revealEmptyCells(newRow, newCol); // Recursively check neighbors
+                }
+            }
+        }
+        
+
```
Comment (pbogre) [inline Minesweeper.java]:
```suggestion
```

File: Minesweeper.java (hunk 21 above)
Comment (Azgorn) [reply Minesweeper.java]: yeah true, since it is the same, i dont think it needs changing

File: Minesweeper.java [hunk 27]
```diff
@@ -118,8 +170,8 @@ private void computeNeighboringBombs(Cell cell) {
                     }
                 }
             }
-
             cell.setNeighboringBombs(neighboringBombs);
+            return neighboringBombs;
```
Comment (pbogre) [inline Minesweeper.java]: i dont think we should make this function return anything if it is also setting the `neighboringBombs` value for the cell, which means we can just get the value from the cell. 
Then, the code on line 121 would become:
```java
// If this cell has no adjacent mines, recursively reveal its neighbors
computeNeighboringBombs(this.cells[row][col])
if (this.cells[row][col].neighboringBombs == 0) {
  ...
}
```
The idea is that you don't want a function to do various things, and this function is either dedicated to setting the cell's `neighboringBombs` or returning a cell's `neighboringBombs`, but shouldnt do both.


Alternatively, the `revealEmptyCells` method could be implemented directly inside of `computeNeighboringBombs` since they serve the same function except that `revealEmptyCells` is dedicated to recursion only, while incorporating it into `computeNeighboringBombs` would make the way we reveal cells itself recursive, which in my opinion better aligns with the idea of a recursive method for revealing cells.

This route would also allow us to take advantage of the fact that we have the ability to reveal cells *before* their neighboring bombs are computed, which effectively means we can skip the "this cell is equal to the selected cell" check and only check if the cell is revealed

File: Minesweeper.java (hunk 21 above)
Comment (pbogre) [reply Minesweeper.java]: the readability problem is still a thing, what does the `d` in `dr` and `dc` stand for?

Comment (Azgorn) [reply Minesweeper.java]: delta, since it's a change, similar to calc, it could be changed smth like "relativeRow" and "relativeCol"

File: Minesweeper.java (hunk 27 above)
Comment (Azgorn) [reply Minesweeper.java]: yeah i agree, i was trying a different thing with it but at the end it's really not needed so it could just be a void

Comment (pbogre) [reply Minesweeper.java]: > yeah i agree, i was trying a different thing with it but at the end it's really not needed so it could just be a void

latest commit addresses this, have a look

File: Minesweeper.java (hunk 21 above)
Comment (pbogre) [reply Minesweeper.java]: latest commit addresses this, have a look

**Comment by pbogre** [comment]
@Azgorn i implemented the changes discussed in the previous review, feel free to review. I am also going to close the other pull request.

**Comment by pbogre** [comment]
oh I think i'm the only one who can review this pr since you're the one who opened it. Just have a look at the code and let me know if you have any comments/objections

**Comment by pbogre** [comment]
This pull request also closes #6 and #16

**Review by Azgorn — COMMENTED** [review]
Everything looks okay, we can merge

**Review by pbogre — APPROVED** [review]
